# Generated by Django 5.0.4 on 2024-04-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_product_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
